[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Heavenston <malolegendrelemaire@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
glfw = "0.36.0"

[build-dependencies]
gl_generator = "0.14.0"