[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Heavenston <malolegendrelemaire@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.21.0"
gl = "0.14.0"